### ISSUE TITLE
Raspbee2 on Pi3

### ISSUE THREAD

**Issue by deimosian** [JCQuintas/mind-components#1]
Hi, I found your post on setting up a Raspbee2 very useful however I hit one snag on my Pi 3B (non plus).

Following the line `dtoverlay=miniuart-bt # use pi3-miniuart-bt if on rp3` I set `dtoverlay=pi3-miniuart-bt`.

This did not work, Zigbee2MQTT would not start. However, after changing it to `dtoverlay=miniuart-bt` it did.

**Comment by JCQuintas** [comment]
Hi @deimosian, thanks for the info and I'm glad it helped you in setting everything up. 😄 

I didn't test the steps on rp3, I only added that because it is specified in the config itself and though it could be useful, so it is possible things have changed. I'll add a comment to make people aware of that. 👍

**Comment by JCQuintas** [comment]
Added a small update to make sure people try both when dealing with rp3, thanks for the input :)
